### ISSUE TITLE
Add Javwhores.com

### ISSUE THREAD

**Issue by syknet69** [holisticdioxide/Ultimate-Whitecream#13]
Not really an issue. Here is the code to add JavWhores.com. Its from the porntrex network and hence uses the same script. 
[javwhores.zip](https://github.com/holisticdioxide/Ultimate-Whitecream/files/1716633/javwhores.zip)

**Comment by holisticdioxide** [comment]
Thank you for your help. It will be implemented soon.

**Comment by holisticdioxide** [comment]
Added in commit 8e815f4
